title: Uma vez em portugal
description: Uma viagem por portugal
author: "Rebecca Ehlers"

theme: minima

base_url: /uma-vez-em-portugal
repository: beccarei/uma-vez-em-portugal

# Minima social links
github_username: beccarei
linkedin_username: rebecca-ehlers-4235b3231
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true
paginate: 5
paginate_path: "/blog/page:num/"


minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
